[pytest]
asyncio_mode = auto
testpaths = tests
addopts = -ra -q --cov=application --cov=domain --cov=infrastructure --cov=presentation --cov-report=term-missing
filterwarnings =
    ignore::DeprecationWarning